from Collections.circular_list import CircularList


circular_list = CircularList()

print("**** Adding elements to list start ****")
circular_list.add_first('a')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_first('b')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_first('c')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_first('d')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_first('e')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_first('f')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_first('g')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')

print("\n\n**** Adding elements to list end ****")
circular_list.add_end('A')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_end('B')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_end('C')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_end('D')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_end('E')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_end('F')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')
circular_list.add_end('G')
circular_list.print_values()
print('Size: ' + str(circular_list.get_size()))
print('------------------------')

print("\n\n**** Verify if the list includes the element ****")

print('Exist a: ' + str(circular_list.includes('a')))
print('Exist 2: ' + str(circular_list.includes('2')))
print('Exist c: ' + str(circular_list.includes('c')))
print('Exist s: ' + str(circular_list.includes('s')))
print('Exist e: ' + str(circular_list.includes('e')))
print('Exist t: ' + str(circular_list.includes('t')))
print('Exist D: ' + str(circular_list.includes('D')))
print('Exist 6: ' + str(circular_list.includes('6')))
print('Exist G: ' + str(circular_list.includes('G')))
print('Exist K: ' + str(circular_list.includes('K')))
print('Exist B: ' + str(circular_list.includes('B')))
print('Exist L: ' + str(circular_list.includes('L')))
circular_list.print_values_reverse()

iterator = circular_list.get_iterator()
print("\n\n**** Print Iterator ****")
for i in range(0, 30):
    print(str(i) + str(iterator.get_current_value()))
    iterator.next()

iterator.reset()
print("\n\n**** Print Iterator Reverse ****")
for i in range(0, 30):
    print(str(i) + ": " + str(iterator.get_current_value()))
    iterator.previous()