from Collections.doubly_linked_list import DoublyLinkedList
from Utils.coordinate import Coordinate


list = DoublyLinkedList()

list.add_last(Coordinate(1,1))
list.add_last(Coordinate(2,2))
list.add_last(Coordinate(3,3))
list.add_last(Coordinate(4,4))
list.add_last(Coordinate(5,5))
list.add_last(Coordinate(6,6))
print('Size: ' + str(list.get_size()))
list.for_each(lambda element, _: print(element))
print('\n\n\n\n')

list.reverse()
print('Size: ' + str(list.get_size()))
list.print_values()
list.reverse()
print('Size: ' + str(list.get_size()))
list.print_values()
list.reverse()
print('Size: ' + str(list.get_size()))
list.print_values()
list.reverse()
print('Size: ' + str(list.get_size()))
list.print_values()
print('\n\n\n\n')


list.remove_last()
print('Size: ' + str(list.get_size()))
list.print_values()
list.remove_last()
print('Size: ' + str(list.get_size()))
list.print_values()
list.remove_last()
print('Size: ' + str(list.get_size()))
list.print_values()
list.remove_last()
print('Size: ' + str(list.get_size()))
list.print_values()
list.remove_last()
print('Size: ' + str(list.get_size()))
list.print_values()
list.remove_last()
print('Size: ' + str(list.get_size()))
list.print_values()
print('\n\n\n\n')

list.add_first(Coordinate(1,1))
print('Size: ' + str(list.get_size()))
list.add_first(Coordinate(2,2))
print('Size: ' + str(list.get_size()))
list.add_first(Coordinate(3,3))
print('Size: ' + str(list.get_size()))
list.add_first(Coordinate(4,4))
print('Size: ' + str(list.get_size()))
list.add_first(Coordinate(5,5))
print('Size: ' + str(list.get_size()))
list.add_first(Coordinate(6,6))
print('Size: ' + str(list.get_size()))
list.print_values()
print('\n\n\n\n')

list.remove_last()
print('Size: ' + str(list.get_size()))
list.remove_last()
print('Size: ' + str(list.get_size()))
list.remove_last()
print('Size: ' + str(list.get_size()))
list.remove_last()
print('Size: ' + str(list.get_size()))
list.remove_last()
print('Size: ' + str(list.get_size()))
list.remove_last()
print('Size: ' + str(list.get_size()))
list.print_values()
print('\n\n\n\n')

list.add_last(Coordinate(1,1))
print('Size: ' + str(list.get_size()))
list.add_last(Coordinate(2,2))
print('Size: ' + str(list.get_size()))
list.add_last(Coordinate(3,3))
print('Size: ' + str(list.get_size()))
list.add_last(Coordinate(4,4))
print('Size: ' + str(list.get_size()))
list.add_last(Coordinate(5,5))
print('Size: ' + str(list.get_size()))
list.add_last(Coordinate(6,6))
print('Size: ' + str(list.get_size()))
list.print_values()
print('Include (4,4): ' + str(list.includes(Coordinate(4,4))))
print('Include (2,2): ' + str(list.includes(Coordinate(2,2))))
print('Include (6,6): ' + str(list.includes(Coordinate(6,6))))
print('\n\n\n\n')

print('Size: ' + str(list.get_size()))
list.print_values()
print('Pop (2,2) ->> ' + str(list.pop_if_exist(Coordinate(2,2))))
print('Size: ' + str(list.get_size()))
list.print_values()
print('Pop (4,4) ->> ' + str(list.pop_if_exist(Coordinate(4,4))))
print('Size: ' + str(list.get_size()))
list.print_values()
print('Pop (6,6) ->> ' + str(list.pop_if_exist(Coordinate(6,6))))
print('Size: ' + str(list.get_size()))
list.print_values()
print('Pop (2,2) ->> ' + str(list.pop_if_exist(Coordinate(2,2))))
print('Pop (4,4) ->> ' + str(list.pop_if_exist(Coordinate(4,4))))
print('Pop (6,6) ->> ' + str(list.pop_if_exist(Coordinate(6,6))))
print('Include (4,4): ' + str(list.includes(Coordinate(4,4))))
print('Include (2,2): ' + str(list.includes(Coordinate(2,2))))
print('Include (6,6): ' + str(list.includes(Coordinate(6,6))))
print('Size: ' + str(list.get_size()))
list.print_values()