from Collections.queue import Queue


queue = Queue()

print("**** Adding elements to queue ****")
queue.enqueue(1)
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
queue.enqueue(2)
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
queue.enqueue(3)
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
queue.enqueue(4)
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
queue.enqueue(5)
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
queue.enqueue(6)
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
queue.enqueue(7)
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')

print("\n\n**** dequeue elements to queue ****")
print('Dequeue: ' + str(queue.dequeue()))
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
print('Dequeue: ' + str(queue.dequeue()))
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
print('Dequeue: ' + str(queue.dequeue()))
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
print('Dequeue: ' + str(queue.dequeue()))
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
print('Dequeue: ' + str(queue.dequeue()))
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
print('Dequeue: ' + str(queue.dequeue()))
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')
print('Dequeue: ' + str(queue.dequeue()))
queue.print_values()
print('Size: ' + str(queue.get_size()))
print('------------------------')